### ISSUE TITLE
Set default font family?

### ISSUE THREAD

**Issue by ktmitton** [ktmitton/azure-devops-feature-flag-manager#6]
The ado ui components use times new roman, if possible we'd like to use the defaults of the ADO environment.

font-family: "Segoe UI VSS (Regular)","Segoe UI","-apple-system",BlinkMacSystemFont,Roboto,"Helvetica Neue",Helvetica,Ubuntu,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";

**Comment by Blaksey** [comment]
https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops
